export const POLICY_PACKS = [
  { id: 'GAMBLING', name: 'Gambling', populated: true },
  { id: 'ADULT', name: 'Adult', populated: true },
  { id: 'ALCOHOL', name: 'Alcohol', populated: true },
  { id: 'CANNABIS', name: 'Cannabis', populated: true },
  { id: 'DATING', name: 'Dating', populated: true },
  { id: 'TOBACCO', name: 'Tobacco', populated: true },
  { id: 'WEAPONS', name: 'Weapons', populated: true },
  { id: 'CRYPTOCURRENCY', name: 'Cryptocurrency', populated: true },
  { id: 'POLITICS', name: 'Politics', populated: true },
  { id: 'WEIGHT_LOSS', name: 'Weight loss', populated: true },
]

export const PACK_KEYWORDS = {
  GAMBLING: {
    en: [
      'gambling',
      'casino',
      'betting',
      'sports betting',
      'sportsbook',
      'bet',
      'wager',
      'slots',
      'poker',
      'lottery',
      'bingo',
      'roulette',
      'blackjack',
      'jackpot',
      'betting bonus',
      'free bets',
      'virtual betting',
    ],
    de: [
      'glücksspiel',
      'wetten',
      'sportwetten',
      'wettanbieter',
      'wettbüro',
      'casino',
      'online casino',
      'lotterie',
      'lotto',
      'poker',
      'roulette',
      'blackjack',
      'jackpot',
    ],
  },
  ADULT: {
    en: [
      'adult content',
      'pornography',
      'porn',
      'xxx',
      'erotic',
      'escort',
      'nude',
      'nudes',
      'onlyfans',
      'camgirl',
      'adult video',
      'sex toy',
      'strip club',
      'swingers',
      'fetish',
      'explicit content',
      'hardcore',
      'softcore',
      'sex chat',
      'adult dating',
    ],
  },
  ALCOHOL: {
    en: [
      'alcohol',
      'beer',
      'wine',
      'whiskey',
      'vodka',
      'rum',
      'liquor',
      'spirits',
      'cocktail',
      'brewery',
      'winery',
      'distillery',
      'champagne',
      'tequila',
      'gin',
      'hard seltzer',
      'happy hour',
      'drink special',
      'alcoholic',
      'booze',
    ],
  },
  CANNABIS: {
    en: [
      'cannabis',
      'marijuana',
      'weed',
      'thc',
      'cbd oil',
      'dispensary',
      'hemp',
      'edibles',
      'vape cart',
      'cannabis shop',
      'hashish',
      'medical marijuana',
      'recreational weed',
      'pre-roll',
      'dab pen',
      'cannabis delivery',
      'cannabis gummies',
      'thc drink',
      'smoke weed',
      '420 shop',
    ],
  },
  DATING: {
    en: [
      'dating',
      'dating app',
      'singles',
      'matchmaking',
      'hookup',
      'tinder',
      'bumble',
      'online dating',
      'find a date',
      'speed dating',
      'dating site',
      'relationship app',
      'meet singles',
      'swipe right',
      'date night app',
      'personals',
      'companion app',
      'blind date',
      'dating ads',
      'local singles',
    ],
  },
  TOBACCO: {
    en: [
      'tobacco',
      'cigarette',
      'cigarettes',
      'cigars',
      'vape',
      'vaping',
      'e-cigarette',
      'nicotine',
      'smoking',
      'smoke shop',
      'hookah',
      'shisha',
      'chewing tobacco',
      'snus',
      'nicotine pouch',
      'vape pen',
      'tobacco shop',
      'menthol',
      'rolling tobacco',
      'cigar lounge',
    ],
  },
  WEAPONS: {
    en: [
      'weapons',
      'firearm',
      'firearms',
      'gun shop',
      'ammunition',
      'ammo',
      'handgun',
      'rifle',
      'shotgun',
      'pistol',
      'assault rifle',
      'tactical gear',
      'gun store',
      'weapon sale',
      'holster',
      'suppressor',
      'ballistic',
      'armory',
      'airsoft gun',
      'concealed carry',
    ],
  },
  CRYPTOCURRENCY: {
    en: [
      'cryptocurrency',
      'bitcoin',
      'ethereum',
      'crypto',
      'crypto exchange',
      'nft',
      'token sale',
      'altcoin',
      'buy bitcoin',
      'crypto trading',
      'dogecoin',
      'binance',
      'coinbase',
      'defi',
      'crypto wallet',
      'memecoin',
      'crypto airdrop',
      'web3 token',
      'bitcoin mining',
      'crypto promo',
    ],
  },
  POLITICS: {
    en: [
      'politics',
      'political ad',
      'election',
      'political party',
      'campaign rally',
      'vote for',
      'ballot',
      'referendum',
      'political donation',
      'super pac',
      'partisan',
      'legislature',
      'senate race',
      'presidential',
      'political action',
      'campaign ad',
      'political candidate',
      'primary election',
      'political mailer',
      'vote campaign',
    ],
  },
  WEIGHT_LOSS: {
    en: [
      'weight loss',
      'diet pills',
      'fat burner',
      'slimming',
      'lose weight',
      'weight loss pill',
      'detox tea',
      'appetite suppressant',
      'diet shake',
      'waist trainer',
      'fat loss',
      'slim tea',
      'diet supplement',
      'weight loss clinic',
      'crash diet',
      'calorie blocker',
      'slim down',
      'belly fat',
      'weight loss shake',
      'diet drops',
    ],
  },
}

export function packById(id) {
  return POLICY_PACKS.find((pack) => pack.id === id) || null
}

export function keywordsForPack(id) {
  const languages = PACK_KEYWORDS[id] || {}
  return Object.entries(languages).flatMap(([language, words]) =>
    words.map((keyword) => ({ keyword, language, category: id })),
  )
}
